// inventory dashboard implementation
'use client'

import { useMemo, useState } from 'react'
import { Bell, Boxes, ChevronDown, ChevronLeft, ChevronRight, CircleHelp, Download, Ellipsis, FileText, Grid2X2, LayoutDashboard, Leaf, List, MapPin, Menu, Package, Plus, Search, Settings, Sprout, Tag, TrendingUp, Truck, Users, X } from 'lucide-react'

const items = [
  { name: 'Monstera Deliciosa', category: 'Tropical plant', cost: '$48.00', stock: '38', status: 'In Stock' },
  { name: 'Terracotta Classic Pot', category: 'Planter', cost: '$24.00', stock: '112', status: 'In Stock' },
  { name: 'Fiddle Leaf Fig', category: 'Indoor plant', cost: '$68.00', stock: '24', status: 'In Stock' },
  { name: 'Handwoven Basket', category: 'Plant accessory', cost: '$36.00', stock: '9', status: 'Low stock' },
  { name: 'Snake Plant', category: 'Low-light plant', cost: '$32.00', stock: '0', status: 'Out of stock' },
  { name: 'Speckled Stone Pot', category: 'Planter', cost: '$29.00', stock: '61', status: 'In Stock' },
  { name: 'String of Pearls', category: 'Succulent', cost: '$26.00', stock: '17', status: 'In Stock' },
]
const nav = [['Overview', LayoutDashboard], ['Inventory', Package], ['Stock movements', TrendingUp], ['Suppliers', Truck], ['Categories', Tag], ['Locations', MapPin], ['Reports', FileText], ['Team', Users]] as const

export default function Page() {
  const [active, setActive] = useState('Overview'), [query, setQuery] = useState(''), [filter, setFilter] = useState('All'), [selected, setSelected] = useState<string[]>([]), [grid, setGrid] = useState(false), [notice, setNotice] = useState(false)
  const filtered = useMemo(() => items.filter((item) => (item.name + item.category).toLowerCase().includes(query.toLowerCase()) && (filter === 'All' || item.status === filter)), [query, filter])
  const select = (name: string) => setSelected((s) => s.includes(name) ? s.filter((x) => x !== name) : [...s, name])
  const go = (label: string) => { setActive(label); setQuery(''); setFilter('All'); setSelected([]) }
  return <main className="min-h-screen bg-[#e9eee9] p-0 text-[#253129] md:p-5 lg:p-8"><div className="mx-auto flex min-h-[calc(100vh-2rem)] max-w-[1600px] overflow-hidden rounded-none border border-[#d6ded7] bg-[#fbfcfa] shadow-[0_18px_50px_rgba(46,67,52,0.08)] md:rounded-[22px]">
    <aside className="hidden w-[220px] shrink-0 flex-col bg-[#dcefe0] px-4 py-5 md:flex"><div className="mb-9 flex items-center gap-2 px-2 text-[17px] font-semibold"><div className="flex size-8 items-center justify-center rounded-[10px] bg-[#316742] text-white"><Sprout className="size-4" /></div>leaf & co.<ChevronDown className="ml-auto size-4 text-[#66816d]" /></div><nav className="flex flex-col gap-1"><p className="mb-2 px-3 text-[10px] font-semibold tracking-[0.16em] text-[#75917b]">INVENTORY</p>{nav.map(([label, Icon]) => <button key={label} onClick={() => go(label)} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-left text-[13px] ${active === label ? 'bg-white font-medium text-[#1e3d28] shadow-sm' : 'text-[#597360] hover:bg-white/60'}`}><Icon className="size-[17px]" />{label}</button>)}</nav><div className="mt-auto flex flex-col gap-1"><button className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-[13px] text-[#597360]"><CircleHelp className="size-[17px]" />Help center</button><button onClick={() => go('Settings')} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-[13px] ${active === 'Settings' ? 'bg-white font-medium' : 'text-[#597360]'}`}><Settings className="size-[17px]" />Settings</button></div></aside>
    <section className="min-w-0 flex-1"><header className="flex h-[76px] items-center gap-3 border-b border-[#e5e9e5] px-5 md:px-7"><button className="flex size-9 items-center justify-center rounded-lg border md:hidden"><Menu className="size-4" /></button><div className="relative max-w-[410px] flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-[#9baa9f]" /><input aria-label="Search inventory" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search items..." className="h-10 w-full rounded-xl border border-[#e3e9e3] bg-white pl-10 text-sm outline-none focus:border-[#8bb795]" /></div><Bell className="ml-auto size-[18px] text-[#829187]" /><div className="hidden items-center gap-2 sm:flex"><div className="flex size-9 items-center justify-center rounded-full bg-[#bed5c2] text-sm font-semibold text-[#365d40]">RA</div><div className="hidden lg:block"><p className="text-[13px] font-medium">Rayan Anderson</p><p className="text-[11px] text-[#8a998e]">Store manager</p></div><ChevronDown className="size-4 text-[#96a39a]" /></div></header>
    <div className="px-5 py-7 md:px-7 md:py-8">{active === 'Overview' && <Overview />}{active === 'Inventory' && <Inventory filtered={filtered} filter={filter} setFilter={setFilter} query={query} setQuery={setQuery} selected={selected} select={select} grid={grid} setGrid={setGrid} setNotice={setNotice} />}{active === 'Stock movements' && <Movement />}{active === 'Suppliers' && <Suppliers />}{!['Overview', 'Inventory', 'Stock movements', 'Suppliers'].includes(active) && <Placeholder label={active} />}</div></section></div>{selected.length > 0 && <div className="fixed bottom-5 left-1/2 flex -translate-x-1/2 items-center gap-3 rounded-2xl border bg-white px-4 py-3 text-sm shadow-xl"><b>{selected.length} selected</b><button className="flex items-center gap-2 rounded-lg border px-3 py-2"><Download className="size-4" />Export</button><button onClick={() => setSelected([])} aria-label="Clear selection"><X className="size-4" /></button></div>}{notice && <div className="fixed bottom-5 right-5 flex items-center gap-3 rounded-xl bg-[#316742] px-4 py-3 text-sm text-white shadow-xl">Item added to inventory<button onClick={() => setNotice(false)} aria-label="Dismiss"><X className="size-4" /></button></div>}</main>
}

function Overview() { return <><Heading eyebrow="WELCOME BACK" title="Greenhouse Overview" subtitle="Track and manage your store's inventory at a glance" /><div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><Stat icon={Boxes} label="TOTAL ITEMS" value="261" change="+12" tone="up" /><Stat icon={Leaf} label="HEALTHY STOCK" value="198" change="+8" tone="up" /><Stat icon={Package} label="LOW STOCK" value="32" change="+3" tone="down" /><Stat icon={Tag} label="OUT OF STOCK" value="1" change="0" tone="neutral" /></div><div className="mt-8 rounded-2xl border border-[#e3e9e3] bg-white p-6"><h2 className="mb-6 text-lg font-semibold">Recent Activity</h2>{['Monstera received · +15 units from Green Valley Nursery','Low stock alert · Handwoven Basket below threshold','Snake Plant out of stock · Consider reordering soon','Pot inventory used · -5 Terracotta Classic Pots'].map((text, i) => <div key={text} className="flex justify-between border-b border-[#edf0ed] py-4 text-sm last:border-0"><span>{text}</span><span className="text-xs text-[#a0aaa2]">{i + 2} hours ago</span></div>)}</div></> }
function Inventory({ filtered, filter, setFilter, query, setQuery, selected, select, grid, setGrid, setNotice }: any) { return <><div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><Heading eyebrow="STORE INVENTORY" title="Inventory" subtitle="Manage plants, pots, and accessories" /><button onClick={() => setNotice(true)} className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-[#316742] px-4 text-sm font-medium text-white"><Plus className="size-4" />Add item</button></div><div className="mb-7 grid grid-cols-2 gap-3 xl:grid-cols-4"><Stat icon={Boxes} label="TOTAL ITEMS" value="261" change="+12" tone="up" /><Stat icon={Leaf} label="HEALTHY STOCK" value="198" change="+8" tone="up" /><Stat icon={Package} label="LOW STOCK" value="32" change="+3" tone="down" /><Stat icon={Tag} label="OUT OF STOCK" value="1" change="0" tone="neutral" /></div><div className="mb-4 flex flex-col gap-3 lg:flex-row lg:items-center"><div className="relative flex-1 sm:max-w-[340px]"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-[#9baa9f]" /><input aria-label="Search inventory items" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search by name..." className="h-10 w-full rounded-xl border border-[#e3e9e3] bg-white pl-10 text-sm outline-none" /></div><div className="flex gap-1 rounded-xl bg-[#f0f4f0] p-1 text-xs font-medium text-[#7f8e83]">{['All', 'In Stock', 'Low stock', 'Out of stock'].map((x) => <button key={x} onClick={() => setFilter(x)} className={`rounded-lg px-3 py-2 ${filter === x ? 'bg-white text-[#31543a] shadow-sm' : ''}`}>{x}</button>)}</div><div className="hidden rounded-xl border bg-white p-1 sm:flex"><button onClick={() => setGrid(true)} className={`p-1.5 ${grid ? 'bg-[#e4f1e5] text-[#316742]' : ''}`}><Grid2X2 className="size-4" /></button><button onClick={() => setGrid(false)} className={`p-1.5 ${!grid ? 'bg-[#e4f1e5] text-[#316742]' : ''}`}><List className="size-4" /></button></div></div>{grid ? <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-3">{filtered.map((item: any) => <Card key={item.name} item={item} selected={selected.includes(item.name)} onSelect={() => select(item.name)} />)}</div> : <div className="overflow-hidden rounded-2xl border border-[#e3e9e3] bg-white"><div className="hidden grid-cols-[40px_2fr_1fr_1fr_1fr] border-b bg-[#fcfdfb] px-4 py-3 text-[11px] font-semibold uppercase tracking-[0.08em] text-[#98a49b] md:grid"><span /> <span>Item</span><span>Category</span><span>Cost / stock</span><span>Status</span></div>{filtered.map((item: any) => <Row key={item.name} item={item} selected={selected.includes(item.name)} onSelect={() => select(item.name)} />)}</div>}<p className="mt-5 text-xs text-[#8b998e]">Showing {filtered.length} of {items.length} items</p></> }
function Heading({ eyebrow, title, subtitle }: any) { return <div className="mb-7"><p className="mb-2 text-[11px] font-semibold uppercase tracking-[0.13em] text-[#84a08a]">{eyebrow}</p><h1 className="text-[30px] font-semibold tracking-[-0.04em] text-[#213529]">{title}</h1><p className="mt-1 text-sm text-[#829187]">{subtitle}</p></div> }
function Stat({ icon: Icon, label, value, change, tone }: any) { return <div className="rounded-2xl border border-[#e3e9e3] bg-white p-4"><div className="flex items-center gap-2 text-[11px] font-semibold text-[#738178]"><Icon className="size-4 text-[#85a38b]" />{label}<Ellipsis className="ml-auto size-4 text-[#b0bab1]" /></div><div className="mt-4 text-[25px] font-semibold">{value}</div><div className={`mt-1 text-xs ${tone === 'up' ? 'text-[#3c9561]' : tone === 'down' ? 'text-[#d66c63]' : 'text-[#7f8e83]'}`}>{change}<span className="ml-1 text-[#9aa59c]">Last 7 days</span></div></div> }
function Row({ item, selected, onSelect }: any) { return <div className="grid grid-cols-[1fr_auto] items-center gap-3 border-b border-[#edf0ed] px-4 py-3 last:border-0 md:grid-cols-[40px_2fr_1fr_1fr_1fr]"><button onClick={onSelect} aria-label={`Select ${item.name}`} className={`hidden size-4 rounded border md:block ${selected ? 'border-[#316742] bg-[#316742] text-white' : 'border-[#cbd5cc]'}`}>{selected ? '✓' : ''}</button><div className="flex min-w-0 items-center gap-3"><img src="/plant-products.png" alt="" className="size-10 rounded-xl object-cover" /><div><p className="truncate text-sm font-medium">{item.name}</p><p className="text-xs text-[#94a098]">{item.category}</p></div></div><span className="hidden text-sm text-[#66746a] md:block">{item.category}</span><span className="hidden text-sm md:block">{item.cost}<small className="block text-xs text-[#a0aaa2]">Stock {item.stock}</small></span><Status status={item.status} /></div> }
function Card({ item, selected, onSelect }: any) { return <div className="overflow-hidden rounded-2xl border bg-white"><div className="relative h-40 bg-[#edf4ee]"><img src="/plant-products.png" alt="" className="size-full object-cover" /><button onClick={onSelect} className={`absolute right-3 top-3 size-6 rounded-full border ${selected ? 'bg-[#316742] text-white' : 'bg-white/90 text-transparent'}`}>✓</button></div><div className="p-4"><div className="flex justify-between gap-2"><div><h3 className="text-sm font-medium">{item.name}</h3><p className="mt-1 text-xs text-[#8e9b91]">{item.category}</p></div><Status status={item.status} /></div><div className="mt-4 flex justify-between text-sm"><span>{item.cost}</span><span className="text-[#8e9b91]">{item.stock} in stock</span></div></div></div> }
function Status({ status }: any) { const styles: any = { 'In Stock': 'bg-[#e3f5e8] text-[#328354]', 'Low stock': 'bg-[#fff0d8] text-[#be761b]', 'Out of stock': 'bg-[#fde3e0] text-[#c55f58]' }; return <span className={`justify-self-end whitespace-nowrap rounded-full px-2.5 py-1 text-[11px] font-medium ${styles[status]}`}>● {status}</span> }
function Movement() { return <><Heading eyebrow="TRACKING" title="Stock Movements" subtitle="All inventory additions, removals, and adjustments" /><div className="overflow-hidden rounded-2xl border bg-white">{['Monstera Deliciosa · Received · +15 units · Mar 15, 2024','Terracotta Pot · Used · -5 units · Mar 14, 2024','Fiddle Leaf Fig · Received · +10 units · Mar 13, 2024','Handwoven Basket · Damaged · -2 units · Mar 12, 2024'].map((x) => <div key={x} className="border-b p-5 text-sm last:border-0">{x}</div>)}</div></> }
function Suppliers() { return <><Heading eyebrow="PARTNERS" title="Suppliers" subtitle="Manage your supplier contacts and orders" /><div className="grid gap-4 md:grid-cols-3">{['Green Valley Nursery','Premium Pots Inc','Coastal Supplies'].map((x) => <div key={x} className="rounded-2xl border bg-white p-5"><h3 className="font-semibold">{x}</h3><p className="mt-2 text-sm text-[#66746a]">Primary inventory supplier</p><span className="mt-4 inline-block rounded-full bg-[#e3f5e8] px-2 py-1 text-[11px] text-[#328354]">Active</span></div>)}</div></> }
function Placeholder({ label }: { label: string }) { return <><Heading eyebrow="MANAGE" title={label} subtitle={`${label} management for your inventory workspace`} /><div className="flex h-96 items-center justify-center rounded-2xl border border-dashed border-[#e3e9e3]"><div className="text-center"><Package className="mx-auto mb-4 size-12 text-[#b8c6b9]" /><p className="text-[#829187]">{label} management coming soon</p></div></div></> }
